create table if not exists dev_factory_tracking_chart_tree(
dev_fact_tracking_id Integer not null,
view_tree_effective_date varchar(255) null,
view_tree_code Integer null,
view_tree_description varchar(255) null,
graph_design1 varchar(255) null,
graph_design1_desc varchar(255) null,
graph_design2 varchar(255) null,
graph_design2_desc varchar(255) null,
graph_design3 varchar(255) null,
graph_design3_desc varchar(255) null,
graph_design4 varchar(255) null,
graph_design4_desc varchar(255) null,
graph_design5 varchar(255) null,
graph_design5_desc varchar(255) null,
graph_design6 varchar(255) null,
graph_design6_desc varchar(255) null,
graph_design7 varchar(255) null,
graph_design7_desc varchar(255) null,
creation_date varchar(255) null,
modified_date varchar(255) null,
entity_state varchar(255) null,
constraint dev_factory_tracking_chart_tree_pk primary key(dev_fact_tracking_id));